### ISSUE TITLE
Selecting anything as repeat interval hides select card field and prevents form from being submitted.

### ISSUE THREAD

**Issue by johnsonjake** [mohnish/money#60]
When creating a new bill I selected "monthly" for the repeat interval. The "select card" field became hidden and click the button does nothing. the console in chrome says: `An invalid form control with name='payment_source_id' is not focusable.`

in firefox a validation notification pops up in the top left corner of the page: http://i.imgur.com/6e3hViz.png

it seems selecting anything other than "never" completely breaks the form.

**Comment by mohnish** [comment]
Hey @johnsonjake. In order to create non-recurring bills, the user needs to have a card added to their profile. you can do it from the cards page. For bills that are recurring, you won't have the option to select a card right away. this is a feature. it enables the users to make payments from the payments page, which you can reach by clicking on the bill that you've created. for the missing `payment_source_id` issue, i've filed an issue https://github.com/mohnish/money/issues/61
will fix that behavior asap. thanks.

**Comment by mohnish** [comment]
fixed in https://github.com/mohnish/money/issues/61
